name: Release

on:
  pull_request_target:
    branches: [master]
    types: [closed]

permissions:
  contents: write

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version, Commit & Tag
        id: bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: bash scripts/bump_and_tag.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: v${{ steps.bump.outputs.new_version }}

      - name: Upload to Steam Workshop
        env:
          STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_WORKSHOP_ITEM_ID: ${{ secrets.STEAM_WORKSHOP_ITEM_ID }}
          NEW_VERSION: ${{ steps.bump.outputs.new_version }}
        run: |
          bash scripts/upload_workshop.sh \
            "$STEAM_APP_ID" \
            "$STEAM_USERNAME" \
            "$STEAM_PASSWORD" \
            "$STEAM_WORKSHOP_ITEM_ID" \
            "$NEW_VERSION"
