name: Release

on:
  push:
    branches:
      - master
  pull_request:  # Run on PRs for testing workshop upload
  workflow_dispatch:

jobs:
  bump-version-and-release:
    name: Bump version & Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Bump version in mod.info
        id: bump
        run: |
          VERSION=$(grep '^version=' mod.info | cut -d'=' -f2)
          IFS='.' read -r MAJ MIN PATCH <<< "$VERSION"
          PATCH=$((PATCH+1))
          NEW_VERSION="$MAJ.$MIN.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          sed -i "s/^version=.*/version=$NEW_VERSION/" mod.info
          git add mod.info

      - name: Commit and Tag
        run: |
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}"
          git tag "v${{ steps.bump.outputs.new_version }}"

      - name: Push tags
        run: git push origin master --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          name: v${{ steps.bump.outputs.new_version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # --- Steam Workshop Upload ---
  # TODO: After testing, restrict workshop upload to release pushes only
      - name: Create Steam Workshop VDF
        env:
          STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
          STEAM_WORKSHOP_ITEM_ID: ${{ secrets.STEAM_WORKSHOP_ITEM_ID }}
        run: |
          cat > workshop_build_item.vdf <<EOF
          "workshopitem"
          {
            "appid" "$STEAM_APP_ID"
            "contentfolder" "${{ github.workspace }}"
            "previewfile" "poster.png"
            "visibility" "0"
            "changenote" "Release v${{ steps.bump.outputs.new_version }}"
            "publishedfileid" "$STEAM_WORKSHOP_ITEM_ID"
          }
          EOF

      - name: Install SteamCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y steamcmd

      - name: Upload to Steam Workshop
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: |
          steamcmd +login $STEAM_USERNAME $STEAM_PASSWORD +workshop_build_item $(pwd)/workshop_build_item.vdf +quit

