name: Test Scripts

on:
  pull_request:
    branches: [master]
    paths:
      - 'scripts/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/release.yml'
  # Manual trigger to test workflows
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test bump_and_tag.sh dry-run
        run: |
          echo "version=1.2.3" > mod.info
          bash scripts/bump_and_tag.sh --dry-run

      - name: Test upload_workshop.sh dry-run
        run: |
          bash scripts/upload_workshop.sh --dry-run 480 user pass 999999 1.2.3
      
      - name: Debug SteamCMD image layout
        run: |
          echo "Inspecting SteamCMD Docker image for entrypoint and file paths"
          docker pull cm2network/steamcmd:latest
          # Show configured entrypoint
          docker image inspect cm2network/steamcmd:latest --format 'Entrypoint: {{json .Config.Entrypoint}}'
          # Find steamcmd scripts under /home/steam
          docker run --rm cm2network/steamcmd:latest sh -c "find /home/steam -maxdepth 3 -type f -name 'steamcmd*' 2>/dev/null"
