name: Steam Workshop Upload

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

jobs:
  upload-workshop:
    name: Upload to Steam Workshop
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Read version from mod.info
        id: version
        run: |
          VERSION=$(grep '^version=' mod.info | cut -d'=' -f2)
          echo "v=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Steam Workshop VDF
        run: |
          cat > workshop_build_item.vdf <<EOF
          "workshopitem"
          {
            "appid" "${{ secrets.STEAM_APP_ID }}"
            "contentfolder" "${{ github.workspace }}"
            "previewfile" "poster.png"
            "visibility" "0"
            "changenote" "Release v${{ steps.version.outputs.v }}"
            "publishedfileid" "${{ secrets.STEAM_WORKSHOP_ITEM_ID }}"
          }
          EOF

      - name: Upload to Steam Workshop via Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            cm2network/steamcmd:latest \
            +login "${{ secrets.STEAM_USERNAME }}" "${{ secrets.STEAM_PASSWORD }}" \
            +workshop_build_item "/workspace/workshop_build_item.vdf" \
            +quit
